config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'homes#index'
  resources :captain_forms
  get '/captain_account', to: 'homes#captain_account'
  get '/create_account', to: 'accounts#create_account'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/captain_form.rb
class CaptainForm < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :captain_form
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def create_account
    response = StripeService.create_account(current_user, captain_account_path, root_path)
    if response.success
      redirect_to response.url
    else
      flash[:error] = 'Account Successfully connected'
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/captain_forms_controller.rb
class CaptainFormsController < ApplicationController

  def new
    @hostel_captain_request = CaptainForm.new
  end

  def create
    if current_user.stripe_account_id.present?
      @hostel_captain_request = CaptainForm.new(captain_form_params)
      @hostel_captain_request.user = current_user
      if @hostel_captain_request.save
        flash[:success] = 'Your request is being sent.You will get response shortly.'
        redirect_to root_path
      else
        render :new
      end
    else
      flash[:error] = 'You first need to connect your account'
      redirect_to new_captain_form_path
    end
  end


  private

  def captain_form_params
    params.require(:captain_form).permit(:image, :detail)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def index

  end

  def captain_account

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/captain_forms/new.html.erb
<main class="main h-100" role="main">
  <div class="container h-100">
    <div class="row align-items-center h-100">
      <% if current_user.captain_form.present? %>
       <h2>Your request is currently in progress</h2>
        <% else %>
        <div class="col-sm-10 col-md-8 col-lg-6 mx-auto my-4">
          <div class="text-center">
            <h1 class="h3">Request to be a Hostel Captain to Get A Night off Your Stay</h1>
            <p class="lead">
              If approved, you'll get a night off your stay once you organize two events
              that get at least ten guests each or three events that get at least
              five guests each.
            </p>
          </div>
          <div class="card">






            <div class="m-sm-4">
              <%= form_for(@hostel_captain_request) do |f| %>
                <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                <div class="form-group">
                      <span class="btn btn-primary btn-file">
                        <i class="fas fa-upload"></i> Upload
                        <%= f.file_field :image, required: true, id: "user_image_upload_file" %>
                      </span>
                </div>
                <div class="form-group">
                  <%= f.text_field :detail,
                                   label: "Write a short sentence or two introducing yourself and a quick idea for something you plan to do as a hostel captain",
                                   required: true,
                                   autofocus: true,
                                   input_html: { class: "form-control form-control-lg"  } %>
                </div>

                <div class="text-center mt-3">
                  <!--disable if user doesn't have an image-->
                  <%= f.submit "Submit", id: "image_conditional_submit", class: "btn btn-lg btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div><!-- /.card -->
        </div>
        <% end %>

    </div><!-- /.row -->
  </div>
</main>

app/views/homes/captain_account.html.erb
<% if current_user.stripe_account_id.present? %>
  <h2>Your Account is already connected</h2>
<% else %>

  <%= link_to 'Create Account', create_account_path, class: 'btn btn-primary' %>
<% end %>

app/views/homes/index.html.erb
Welcome

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01" style="display: flex!important; justify-content: space-between">
    <div class="form-inline pad-right-2">
      <ul class="form-inline navbar-nav mr-auto mt-2 mt-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Apply for captain', new_captain_form_path, :class => 'navbar-link clr-white'  %>
            <%= link_to 'Connect Account',captain_account_path, :class => 'navbar-link clr-white'  %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link clr-white' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link clr-white' %> |
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link clr-white' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripIntegeration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/nav' %>
  <body class="menu-position-side menu-side-left full-screen">
  <div class="success-alert">
    <% flash.each do |key, value| %>
      <div>
        <%= value %>
      </div>
    <% end %>
  </div>
  <br/>
  <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>